### ISSUE TITLE
Missing hardware schematics

### ISSUE THREAD

**Issue by uKL** [hypeapps/black-mirror#1]
Great project!

Could you share schematics and used hardware?

**Comment by hypeapps** [comment]
You only need:
- Raspberry Pi3
- Anbes Super Mini New High-Quality Sound USB 2.0 Microphone Audio Adapter (works with AndroidThings out of the box)
- Compaq 17' 4:3 LCD Display or any suitable screen, tablet, tv etc.

That's all!

**Comment by nanomader** [comment]
You'll need also a double sided acryllic mirror fit to the size of the monitor to make it work like on @hypeapps video.

Great project, BTW!
